import { invoke } from '@tauri-apps/api/core';
import { persistGet, persistSet, persistRemove } from '$lib/persist';

// Text-to-speech for voice-command replies. Two backends:
//   - ElevenLabs (bring-your-own-key) if a key is configured — better voice
//     quality, costs the user's own ElevenLabs credits.
//   - Windows SAPI (tts_speak_sapi in Rust) otherwise — free, zero-setup,
//     Windows-only. On Linux with no key configured, speak() will surface
//     whatever error tts_speak_sapi returns (there's no bundled fallback
//     there) rather than fail silently.

export type TtsKeyStorage = 'keychain' | 'fallback' | 'none';
/** Which plan a voice needs. `own` = cloned/generated by this account (usable
 *  on whatever plan the account has); `unknown` = the API gave no signal. */
export type VoiceTier = 'free' | 'own' | 'paid' | 'unknown';
export interface ElevenLabsVoice { id: string; name: string; tier: VoiceTier; }

interface RawVoice {
  voiceId: string;
  name: string;
  category?: string | null;
  isOwner?: boolean | null;
  freeUsersAllowed?: boolean | null;
  availableForTiers?: string[];
}

/** Premade voices are usable on every plan; an account's own clones are
 *  usable on its plan. Library voices (professional/famous/high_quality) are
 *  the ones that returned 402 for a free key, and ElevenLabs flags them via
 *  `sharing.free_users_allowed` / `available_for_tiers` when it does at all. */
function voiceTier(v: RawVoice): VoiceTier {
  const cat = v.category ?? '';
  if (v.isOwner || cat === 'cloned' || cat === 'generated') return 'own';
  if (cat === 'premade') return 'free';
  const tiers = v.availableForTiers ?? [];
  if (tiers.length > 0) return tiers.includes('free') ? 'free' : 'paid';
  if (v.freeUsersAllowed === false) return 'paid';
  if (v.freeUsersAllowed === true) return 'free';
  if (cat === 'professional' || cat === 'famous' || cat === 'high_quality') return 'paid';
  return 'unknown';
}

/** ElevenLabs' own premade voice roster — confirmed working on a free-tier
 *  account. Used only if `tts_list_elevenlabs_voices` fails (network hiccup,
 *  ElevenLabs API change, etc.) so the picker never dead-ends with nothing
 *  selectable; the live account fetch is still what actually runs normally,
 *  since it also picks up any voices the account has cloned/added. */
const FALLBACK_VOICES: ElevenLabsVoice[] = [
  { id: 'N2lVS1w4EtoT3dr4eOWO', name: 'Callum', tier: 'free' },
  { id: 'CwhRBWXzGAHq8TQ4Fs17', name: 'Roger', tier: 'free' },
  { id: 'nPczCjzI2devNBz1zQrb', name: 'Brian', tier: 'free' },
  { id: 'onwK4e9ZLuTAKqWW03F9', name: 'Daniel', tier: 'free' },
  { id: 'pFZP5JQG7iQjIQuC4Bku', name: 'Lily', tier: 'free' },
  { id: 'pNInz6obpgDQGcFmaJgB', name: 'Adam', tier: 'free' },
  { id: 'pqHfZKP75CvOlQylNhV4', name: 'Bill', tier: 'free' },
  { id: 'EXAVITQu4vr4xnSDxMaL', name: 'Sarah', tier: 'free' },
  { id: 'Xb7hH8MSUJpSbSDYk0k2', name: 'Alice', tier: 'free' },
];

const FALLBACK_KEY_KEY = 'EXILECOMPASS_ELEVENLABS_KEY_FALLBACK_V1'; // disk (settings.json), plaintext — see keyStorage
const VOICE_ID_KEY = 'EXILECOMPASS_ELEVENLABS_VOICE_ID_V1'; // not sensitive — plain localStorage

// ── Reactive state (Svelte 5 runes) ───────────────────────────────────────────

let _hasKey = $state(false);
let _keyStorage = $state<TtsKeyStorage>('none');
let _voices = $state<ElevenLabsVoice[]>([]);
let _voiceId = $state('');
let _speaking = $state(false);
let _error = $state('');

export const ttsState = {
  get hasKey() { return _hasKey; },
  /** Where the ElevenLabs key actually ended up — drives the Settings UI's
   *  "not stored in your system keychain" notice when it's 'fallback'. */
  get keyStorage() { return _keyStorage; },
  /** Voices this account can actually use — fetched from ElevenLabs, not a
   *  hardcoded list (see loadElevenLabsVoices for why that was a problem). */
  get voices() { return _voices; },
  get voiceId() { return _voiceId; },
  get speaking() { return _speaking; },
  get error() { return _error; },
};

// ── Key management ────────────────────────────────────────────────────────

async function readKeychainKey(): Promise<string | null> {
  try {
    return await invoke<string | null>('tts_get_elevenlabs_key_keychain');
  } catch {
    return null; // no OS keychain reachable (e.g. Linux, no keyring daemon)
  }
}

export async function loadTtsSettings(): Promise<void> {
  const savedVoice = window.localStorage.getItem(VOICE_ID_KEY);
  if (savedVoice) _voiceId = savedVoice;

  const keychainKey = await readKeychainKey();
  if (keychainKey) {
    _hasKey = true;
    _keyStorage = 'keychain';
    await loadElevenLabsVoices();
    return;
  }
  const fallbackKey = await persistGet(FALLBACK_KEY_KEY);
  if (fallbackKey) {
    _hasKey = true;
    _keyStorage = 'fallback';
    await loadElevenLabsVoices();
    return;
  }
  _hasKey = false;
  _keyStorage = 'none';
}

/** Save the key: OS keychain if reachable, otherwise the same local
 *  settings.json every other setting uses (flagged via `keyStorage`). */
export async function setElevenLabsKey(key: string): Promise<void> {
  try {
    await invoke('tts_set_elevenlabs_key_keychain', { key });
    await persistRemove(FALLBACK_KEY_KEY); // drop any stale plaintext copy
    _hasKey = true;
    _keyStorage = 'keychain';
  } catch {
    await persistSet(FALLBACK_KEY_KEY, key);
    _hasKey = true;
    _keyStorage = 'fallback';
  }
  await loadElevenLabsVoices();
}

export async function clearElevenLabsKey(): Promise<void> {
  try { await invoke('tts_delete_elevenlabs_key_keychain'); } catch { /* best effort */ }
  await persistRemove(FALLBACK_KEY_KEY);
  _hasKey = false;
  _keyStorage = 'none';
  _voices = [];
}

async function getElevenLabsKey(): Promise<string | null> {
  const keychainKey = await readKeychainKey();
  if (keychainKey) return keychainKey;
  return persistGet(FALLBACK_KEY_KEY);
}

/** Fetch the voices this account can actually use — not a hardcoded preset
 *  list, so it also picks up any voice the account has cloned/added. Falls
 *  back to FALLBACK_VOICES (confirmed-working premade voices) rather than
 *  leaving the picker empty if the fetch itself fails for any reason —
 *  the error is still recorded on `ttsState.error` so it's visible, but a
 *  transient failure here shouldn't leave voice replies with nothing
 *  selectable. */
export async function loadElevenLabsVoices(): Promise<void> {
  const key = await getElevenLabsKey();
  if (!key) { _voices = []; return; }
  try {
    const fetched = await invoke<RawVoice[]>('tts_list_elevenlabs_voices', { apiKey: key });
    _voices = fetched.map((v) => ({ id: v.voiceId, name: v.name, tier: voiceTier(v) }));
  } catch (e) {
    _error = String(e);
    _voices = FALLBACK_VOICES;
  }
  if (!_voiceId || !_voices.some((v) => v.id === _voiceId)) {
    setVoiceId(_voices[0]?.id ?? '');
  }
}

export function setVoiceId(id: string) {
  _voiceId = id;
  window.localStorage.setItem(VOICE_ID_KEY, id);
}

// ── Speaking ──────────────────────────────────────────────────────────────

let _audioEl: HTMLAudioElement | null = null;

function playAudioBytes(bytes: number[]): Promise<void> {
  const blob = new Blob([new Uint8Array(bytes)], { type: 'audio/mpeg' });
  const url = URL.createObjectURL(blob);
  if (_audioEl) {
    _audioEl.pause();
    URL.revokeObjectURL(_audioEl.src);
  }
  const audio = new Audio(url);
  _audioEl = audio;
  return new Promise<void>((resolve) => {
    const cleanup = () => { URL.revokeObjectURL(url); resolve(); };
    audio.onended = cleanup;
    audio.onerror = cleanup;
    void audio.play().catch(cleanup);
  });
}

/** Speak `text` aloud — ElevenLabs if a key is configured, otherwise the free
 *  Windows SAPI fallback. Errors are recorded on `ttsState.error` rather than
 *  thrown, since this is normally fired from a background voice-command
 *  detection with nothing to catch the rejection. */
export async function speak(text: string): Promise<void> {
  const trimmed = text.trim();
  if (!trimmed) return;
  _error = '';
  _speaking = true;
  try {
    const key = await getElevenLabsKey();
    if (key) {
      const bytes = await invoke<number[]>('tts_speak_elevenlabs', {
        text: trimmed,
        apiKey: key,
        voiceId: _voiceId,
      });
      await playAudioBytes(bytes);
    } else {
      await invoke('tts_speak_sapi', { text: trimmed });
    }
  } catch (e) {
    _error = String(e);
  } finally {
    _speaking = false;
  }
}
