import { invoke } from '@tauri-apps/api/core';
import { persistGet, persistSet, persistRemove } from '$lib/persist';

// Text-to-speech for voice-command replies. Two backends:
//   - ElevenLabs (bring-your-own-key) if a key is configured — better voice
//     quality, costs the user's own ElevenLabs credits.
//   - Windows SAPI (tts_speak_sapi in Rust) otherwise — free, zero-setup,
//     Windows-only. On Linux with no key configured, speak() will surface
//     whatever error tts_speak_sapi returns (there's no bundled fallback
//     there) rather than fail silently.

export type TtsKeyStorage = 'keychain' | 'fallback' | 'none';
/** Which plan a voice needs. `own` = cloned/generated by this account (usable
 *  on whatever plan the account has); `unknown` = the API gave no signal. */
export type VoiceTier = 'free' | 'own' | 'paid' | 'unknown';
export interface ElevenLabsVoice { id: string; name: string; tier: VoiceTier; }

interface RawVoice {
  voiceId: string;
  name: string;
  category?: string | null;
  isOwner?: boolean | null;
  freeUsersAllowed?: boolean | null;
  availableForTiers?: string[];
}

/** Premade voices are usable on every plan; an account's own clones are
 *  usable on its plan. Library voices (professional/famous/high_quality) are
 *  the ones that returned 402 for a free key, and ElevenLabs flags them via
 *  `sharing.free_users_allowed` / `available_for_tiers` when it does at all. */
function voiceTier(v: RawVoice): VoiceTier {
  const cat = v.category ?? '';
  if (v.isOwner || cat === 'cloned' || cat === 'generated') return 'own';
  if (cat === 'premade') return 'free';
  const tiers = v.availableForTiers ?? [];
  if (tiers.length > 0) return tiers.includes('free') ? 'free' : 'paid';
  if (v.freeUsersAllowed === false) return 'paid';
  if (v.freeUsersAllowed === true) return 'free';
  if (cat === 'professional' || cat === 'famous' || cat === 'high_quality') return 'paid';
  return 'unknown';
}

/** ElevenLabs' own premade voice roster — confirmed working on a free-tier
 *  account. Used only if `tts_list_elevenlabs_voices` fails (network hiccup,
 *  ElevenLabs API change, etc.) so the picker never dead-ends with nothing
 *  selectable; the live account fetch is still what actually runs normally,
 *  since it also picks up any voices the account has cloned/added. */
const FALLBACK_VOICES: ElevenLabsVoice[] = [
  { id: 'N2lVS1w4EtoT3dr4eOWO', name: 'Callum', tier: 'free' },
  { id: 'CwhRBWXzGAHq8TQ4Fs17', name: 'Roger', tier: 'free' },
  { id: 'nPczCjzI2devNBz1zQrb', name: 'Brian', tier: 'free' },
  { id: 'onwK4e9ZLuTAKqWW03F9', name: 'Daniel', tier: 'free' },
  { id: 'pFZP5JQG7iQjIQuC4Bku', name: 'Lily', tier: 'free' },
  { id: 'pNInz6obpgDQGcFmaJgB', name: 'Adam', tier: 'free' },
  { id: 'pqHfZKP75CvOlQylNhV4', name: 'Bill', tier: 'free' },
  { id: 'EXAVITQu4vr4xnSDxMaL', name: 'Sarah', tier: 'free' },
  { id: 'Xb7hH8MSUJpSbSDYk0k2', name: 'Alice', tier: 'free' },
];

const FALLBACK_KEY_KEY = 'EXILECOMPASS_ELEVENLABS_KEY_FALLBACK_V1'; // disk (settings.json), plaintext — see keyStorage
const VOICE_ID_KEY = 'EXILECOMPASS_ELEVENLABS_VOICE_ID_V1'; // not sensitive — plain localStorage
const OUTPUT_DEVICE_KEY = 'EXILECOMPASS_TTS_OUTPUT_DEVICE_V1'; // device name; absent = system default
const ENGINE_KEY = 'EXILECOMPASS_TTS_ENGINE_V1'; // 'system' | 'offline' | 'elevenlabs'
const OFFLINE_VOICE_KEY = 'EXILECOMPASS_TTS_OFFLINE_VOICE_V1';
const OFFLINE_SPEAKER_KEY = 'EXILECOMPASS_TTS_OFFLINE_SPEAKER_V1';

export type TtsEngine = 'system' | 'offline' | 'elevenlabs';

export interface OfflineVoice {
  id: string;
  name: string;
  description: string;
  sizeMb: number;
  installed: boolean;
  speakers: string[];
}

export interface OfflineDownload {
  id: string;
  received: number;
  total: number | null;
  phase: 'download' | 'extract' | 'done';
}

// ── Reactive state (Svelte 5 runes) ───────────────────────────────────────────

let _hasKey = $state(false);
let _keyStorage = $state<TtsKeyStorage>('none');
let _voices = $state<ElevenLabsVoice[]>([]);
let _voiceId = $state('');
let _speaking = $state(false);
let _error = $state('');
let _outputDevices = $state<string[]>([]);
let _outputDevice = $state<string | null>(null);
let _engine = $state<TtsEngine>('system');
let _offlineVoices = $state<OfflineVoice[]>([]);
let _offlineVoiceId = $state('');
let _offlineSpeaker = $state(0);
let _download = $state<OfflineDownload | null>(null);

export const ttsState = {
  /** Which backend speak() uses. 'elevenlabs' without a key falls back to 'system'. */
  get engine() { return _engine; },
  get offlineVoices() { return _offlineVoices; },
  get offlineVoiceId() { return _offlineVoiceId; },
  get offlineSpeaker() { return _offlineSpeaker; },
  /** In-flight voice download, or null. */
  get download() { return _download; },
  get outputDevices() { return _outputDevices; },
  /** null = system default output. Applies to both ElevenLabs and SAPI. */
  get outputDevice() { return _outputDevice; },
  get hasKey() { return _hasKey; },
  /** Where the ElevenLabs key actually ended up — drives the Settings UI's
   *  "not stored in your system keychain" notice when it's 'fallback'. */
  get keyStorage() { return _keyStorage; },
  /** Voices this account can actually use — fetched from ElevenLabs, not a
   *  hardcoded list (see loadElevenLabsVoices for why that was a problem). */
  get voices() { return _voices; },
  get voiceId() { return _voiceId; },
  get speaking() { return _speaking; },
  get error() { return _error; },
};

// ── Key management ────────────────────────────────────────────────────────

async function readKeychainKey(): Promise<string | null> {
  try {
    return await invoke<string | null>('tts_get_elevenlabs_key_keychain');
  } catch {
    return null; // no OS keychain reachable (e.g. Linux, no keyring daemon)
  }
}

export async function loadTtsSettings(): Promise<void> {
  const savedVoice = window.localStorage.getItem(VOICE_ID_KEY);
  if (savedVoice) _voiceId = savedVoice;

  const savedEngine = window.localStorage.getItem(ENGINE_KEY);
  if (savedEngine === 'system' || savedEngine === 'offline' || savedEngine === 'elevenlabs') {
    _engine = savedEngine;
  }
  _offlineVoiceId = window.localStorage.getItem(OFFLINE_VOICE_KEY) ?? '';
  _offlineSpeaker = parseInt(window.localStorage.getItem(OFFLINE_SPEAKER_KEY) ?? '0', 10) || 0;
  void loadOfflineVoices();
  void subscribeOfflineProgress();

  const keychainKey = await readKeychainKey();
  if (keychainKey) {
    _hasKey = true;
    _keyStorage = 'keychain';
    await loadElevenLabsVoices();
    return;
  }
  const fallbackKey = await persistGet(FALLBACK_KEY_KEY);
  if (fallbackKey) {
    _hasKey = true;
    _keyStorage = 'fallback';
    await loadElevenLabsVoices();
    return;
  }
  _hasKey = false;
  _keyStorage = 'none';
}

/** Save the key: OS keychain if reachable, otherwise the same local
 *  settings.json every other setting uses (flagged via `keyStorage`). */
export async function setElevenLabsKey(key: string): Promise<void> {
  try {
    await invoke('tts_set_elevenlabs_key_keychain', { key });
    await persistRemove(FALLBACK_KEY_KEY); // drop any stale plaintext copy
    _hasKey = true;
    _keyStorage = 'keychain';
  } catch {
    await persistSet(FALLBACK_KEY_KEY, key);
    _hasKey = true;
    _keyStorage = 'fallback';
  }
  await loadElevenLabsVoices();
}

export async function clearElevenLabsKey(): Promise<void> {
  try { await invoke('tts_delete_elevenlabs_key_keychain'); } catch { /* best effort */ }
  await persistRemove(FALLBACK_KEY_KEY);
  _hasKey = false;
  _keyStorage = 'none';
  _voices = [];
}

async function getElevenLabsKey(): Promise<string | null> {
  const keychainKey = await readKeychainKey();
  if (keychainKey) return keychainKey;
  return persistGet(FALLBACK_KEY_KEY);
}

/** Fetch the voices this account can actually use — not a hardcoded preset
 *  list, so it also picks up any voice the account has cloned/added. Falls
 *  back to FALLBACK_VOICES (confirmed-working premade voices) rather than
 *  leaving the picker empty if the fetch itself fails for any reason —
 *  the error is still recorded on `ttsState.error` so it's visible, but a
 *  transient failure here shouldn't leave voice replies with nothing
 *  selectable. */
export async function loadElevenLabsVoices(): Promise<void> {
  const key = await getElevenLabsKey();
  if (!key) { _voices = []; return; }
  try {
    const fetched = await invoke<RawVoice[]>('tts_list_elevenlabs_voices', { apiKey: key });
    _voices = fetched.map((v) => ({ id: v.voiceId, name: v.name, tier: voiceTier(v) }));
  } catch (e) {
    _error = String(e);
    _voices = FALLBACK_VOICES;
  }
  if (!_voiceId || !_voices.some((v) => v.id === _voiceId)) {
    setVoiceId(_voices[0]?.id ?? '');
  }
}

export function setVoiceId(id: string) {
  _voiceId = id;
  window.localStorage.setItem(VOICE_ID_KEY, id);
}

// ── Output device ─────────────────────────────────────────────────────────

export async function loadTtsOutputDevices(): Promise<void> {
  try {
    _outputDevices = await invoke<string[]>('tts_list_output_devices');
  } catch (e) {
    _error = String(e);
    return;
  }
  // Only honor the saved pick if that device is still present — otherwise
  // fall back to the system default rather than erroring on an unplugged
  // headset.
  const saved = window.localStorage.getItem(OUTPUT_DEVICE_KEY);
  _outputDevice = saved && _outputDevices.includes(saved) ? saved : null;
}

export function setTtsOutputDevice(name: string | null) {
  _outputDevice = name;
  if (name) window.localStorage.setItem(OUTPUT_DEVICE_KEY, name);
  else window.localStorage.removeItem(OUTPUT_DEVICE_KEY);
}

// ── Engine selection + offline voices ─────────────────────────────────────

export function setTtsEngine(engine: TtsEngine) {
  _engine = engine;
  window.localStorage.setItem(ENGINE_KEY, engine);
}

export async function loadOfflineVoices(): Promise<void> {
  try {
    _offlineVoices = await invoke<OfflineVoice[]>('tts_offline_voices');
  } catch (e) {
    _error = String(e);
    return;
  }
  const installed = _offlineVoices.filter((v) => v.installed);
  if (!installed.some((v) => v.id === _offlineVoiceId)) {
    setOfflineVoice(installed[0]?.id ?? '');
  }
}

export function setOfflineVoice(id: string) {
  _offlineVoiceId = id;
  if (id) window.localStorage.setItem(OFFLINE_VOICE_KEY, id);
  else window.localStorage.removeItem(OFFLINE_VOICE_KEY);
  const v = _offlineVoices.find((x) => x.id === id);
  if (v && _offlineSpeaker >= Math.max(1, v.speakers.length)) setOfflineSpeaker(0);
}

export function setOfflineSpeaker(index: number) {
  _offlineSpeaker = index;
  window.localStorage.setItem(OFFLINE_SPEAKER_KEY, String(index));
}

let _progressSubscribed = false;
async function subscribeOfflineProgress() {
  if (_progressSubscribed) return;
  _progressSubscribed = true;
  const { listen } = await import('@tauri-apps/api/event');
  await listen<OfflineDownload>('tts-offline-progress', (e) => {
    _download = e.payload.phase === 'done' ? null : e.payload;
  });
}

export async function downloadOfflineVoice(id: string): Promise<void> {
  _error = '';
  _download = { id, received: 0, total: null, phase: 'download' };
  try {
    await invoke('tts_offline_download', { id });
    await loadOfflineVoices();
    setOfflineVoice(id);
  } catch (e) {
    _error = String(e);
  } finally {
    _download = null;
  }
}

export async function removeOfflineVoice(id: string): Promise<void> {
  _error = '';
  try {
    await invoke('tts_offline_remove', { id });
    await loadOfflineVoices();
  } catch (e) {
    _error = String(e);
  }
}

// ── Speaking ──────────────────────────────────────────────────────────────

let _audioEl: HTMLAudioElement | null = null;

function playAudioBytes(bytes: number[]): Promise<void> {
  const blob = new Blob([new Uint8Array(bytes)], { type: 'audio/mpeg' });
  const url = URL.createObjectURL(blob);
  if (_audioEl) {
    _audioEl.pause();
    URL.revokeObjectURL(_audioEl.src);
  }
  const audio = new Audio(url);
  _audioEl = audio;
  return new Promise<void>((resolve) => {
    const cleanup = () => { URL.revokeObjectURL(url); resolve(); };
    audio.onended = cleanup;
    audio.onerror = cleanup;
    void audio.play().catch(cleanup);
  });
}

/** Speak `text` aloud — ElevenLabs if a key is configured, otherwise the free
 *  Windows SAPI fallback. Errors are recorded on `ttsState.error` rather than
 *  thrown, since this is normally fired from a background voice-command
 *  detection with nothing to catch the rejection. */
export async function speak(text: string): Promise<void> {
  const trimmed = text.trim();
  if (!trimmed) return;
  _error = '';
  _speaking = true;
  try {
    const key = _engine === 'elevenlabs' ? await getElevenLabsKey() : null;
    if (_engine === 'elevenlabs' && key) {
      const bytes = await invoke<number[]>('tts_speak_elevenlabs', {
        text: trimmed,
        apiKey: key,
        voiceId: _voiceId,
      });
      if (_outputDevice) {
        await invoke('tts_play_audio', { bytes, deviceName: _outputDevice });
      } else {
        await playAudioBytes(bytes);
      }
    } else if (_engine === 'offline' && _offlineVoiceId) {
      await invoke('tts_offline_speak', {
        text: trimmed,
        voiceId: _offlineVoiceId,
        speaker: _offlineSpeaker,
        speed: 1.0,
        deviceName: _outputDevice,
      });
    } else {
      // 'system', or a chosen engine that isn't usable yet (no key / no voice).
      await invoke('tts_speak_sapi', { text: trimmed, deviceName: _outputDevice });
    }
  } catch (e) {
    _error = String(e);
  } finally {
    _speaking = false;
  }
}
