export interface RelicRegex {
  name: string,
  regex: string,
  values: number[],
  ranges: number[][],
  affix: string,
}
export const relicRegex: RelicRegex[] = [
{
  name: "#% increased maximum Life",
  regex: "m life$",
  values: [],
  ranges: [[5,25]],
  affix: "PREFIX",
}, 
{
  name: "#% increased maximum Honour",
  regex: "m honour$",
  values: [],
  ranges: [[9,45]],
  affix: "PREFIX",
}, 
{
  name: "#% increased Honour restored",
  regex: "ored$",
  values: [],
  ranges: [[6,45]],
  affix: "PREFIX",
}, 
{
  name: "Monsters have #% chance to drop double Sacred Water",
  regex: "p do",
  values: [],
  ranges: [[5,15]],
  affix: "SUFFIX",
}, 
{
  name: "Fountains have #% chance to grant double Sacred Water",
  regex: "^fou",
  values: [],
  ranges: [[5,15]],
  affix: "SUFFIX",
}, 
{
  name: "#% reduced Merchant Prices",
  regex: "rice",
  values: [],
  ranges: [[-10,-6]],
  affix: "SUFFIX",
}, 
{
  name: "Restore # Honour on killing a Boss",
  regex: "r on k",
  values: [],
  ranges: [[40,150]],
  affix: "SUFFIX",
}, 
{
  name: "Restore # Honour on venerating a Maraketh Shrine",
  regex: "on ve",
  values: [],
  ranges: [[25,75]],
  affix: "SUFFIX",
}, 
{
  name: "Gain # Sacred Water at the start of the Trial",
  regex: "rial$",
  values: [],
  ranges: [[30,59]],
  affix: "PREFIX",
}, 
{
  name: "Gain # Sacred Water when you complete a Room",
  regex: "u com",
  values: [],
  ranges: [[11,30]],
  affix: "SUFFIX",
}, 
{
  name: "Restore # Honour on room completion",
  regex: "etion$",
  values: [],
  ranges: [[10,30]],
  affix: "SUFFIX",
}, 
{
  name: "#% chance to Avoid gaining an Affliction",
  regex: "id g",
  values: [],
  ranges: [[6,15]],
  affix: "SUFFIX",
}, 
{
  name: "Monsters take #% increased Damage",
  regex: "^monsters t",
  values: [],
  ranges: [[11,30]],
  affix: "PREFIX",
}, 
{
  name: "Rare Monsters take #% increased Damage",
  regex: "re monsters t",
  values: [],
  ranges: [[11,30]],
  affix: "PREFIX",
}, 
{
  name: "Bosses take #% increased Damage",
  regex: "sses ta",
  values: [],
  ranges: [[11,30]],
  affix: "PREFIX",
}, 
{
  name: "The Merchant has an additional Choice",
  regex: "hoi",
  values: [1],
  ranges: [],
  affix: "PREFIX",
}, 
{
  name: "#% increased quantity of Relics dropped by Monsters",
  regex: "cs d",
  values: [],
  ranges: [[6,20]],
  affix: "SUFFIX",
}, 
{
  name: "#% increased Armour, Evasion and Energy Shield",
  regex: "d energy shield$",
  values: [],
  ranges: [[20,70]],
  affix: "PREFIX",
}, 
{
  name: "Traps deal #% reduced Damage",
  regex: "ps d",
  values: [],
  ranges: [[-10,-5]],
  affix: "PREFIX",
}, 
{
  name: "#% increased Movement Speed",
  regex: "\\d+% increased mo",
  values: [],
  ranges: [[3,10]],
  affix: "PREFIX",
}, 
{
  name: "# metres to Dodge Roll distance",
  regex: "to do",
  values: [],
  ranges: [[3,7]],
  affix: "SUFFIX",
}, 
{
  name: "#% reduced Slowing Potency of Debuffs on You",
  regex: "n you$",
  values: [],
  ranges: [[-20,-8]],
  affix: "SUFFIX",
}, 
{
  name: "Hits against you have #% reduced Critical Damage Bonus",
  regex: "st y",
  values: [],
  ranges: [[12,25]],
  affix: "SUFFIX",
}, 
{
  name: "When you gain a Key #% chance to gain another",
  regex: "her$",
  values: [],
  ranges: [[7,16]],
  affix: "PREFIX",
}, 
{
  name: "Restore # Honour on picking up a Key",
  regex: "ey$",
  values: [],
  ranges: [[25,75]],
  affix: "SUFFIX",
}, 
{
  name: "#% to Honour Resistance",
  regex: "o hon",
  values: [],
  ranges: [[8,40]],
  affix: "SUFFIX",
}, 
{
  name: "#% to Maximum Honour Resistance",
  regex: "\\d+% to m",
  values: [],
  ranges: [[2,5]],
  affix: "SUFFIX",
}, 
{
  name: "#% increased quantity of Keys dropped by Monsters",
  regex: "f ke",
  values: [],
  ranges: [[6,25]],
  affix: "SUFFIX",
}, 
{
  name: "#% chance if you were to lose all your Honour to have 1 Honour instead",
  regex: "1 h",
  values: [],
  ranges: [[5,12]],
  affix: "PREFIX",
}, 
{
  name: "#% chance for each of your Keys to upgrade on completing a Floor",
  regex: "oor$",
  values: [],
  ranges: [[3,9]],
  affix: "PREFIX",
}]